apiVersion: v1
kind: Pod
metadata:
  name: devwebapp
  labels:
    app: devwebapp
spec:
  serviceAccountName: vault-auth
  containers:
    - name: devwebapp
      image: nginx
      env:
        - name: VAULT_ADDR
          value: "https://vault.vault.svc.cluster.local:8200"
