

apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: namespace-b
  # Using a different service account
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: k8s-secret-app200
      optional: true
      secretNamespace: test


