apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: vault
spec:
  containers:
  - image: nginx
    name: nginx
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: static-secret1
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: static-secret1
          key: password
  
