---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultPKISecret
metadata:
  namespace: default
  name: pki
spec:
  vaultAuthRef: example2
  mount: pki_int
  name: example-dot-com
  commonName: opus111.example.com
  format: pem
  expiryOffset: 1s
  ttl: 60s
  #namespace: tenant-1
  destination:
    create: true
    name: pki1
